[package]
name = "rignore"
version = "0.6.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rignore"
crate-type = ["cdylib"]

[dependencies]
ignore = "0.4.23"
pyo3 = "0.25.1"
